### ISSUE TITLE
Suggest to increase cpu operation?

### ISSUE THREAD

**Issue by rgzn-aiyun** [PeterouZh/CIPS-3D#10]
Hello, can you increase the cpu operating parameters?

**Comment by PeterouZh** [comment]
Sorry, could you explain what is "cpu operating parameters"?

**Comment by rgzn-aiyun** [comment]
> Sorry, could you explain what is "cpu operating parameters"?

Add a parameter, it can also run on the cpu.

**Comment by PeterouZh** [comment]
The code is written without considering running on the CPU. 

If you want to run on the CPU, some functions may need to be rewritten in NumPy. Sorry, I have no plans to implement this feature.
