### ISSUE TITLE
How to trans the result into 3D mesh

### ISSUE THREAD

**Issue by rainsoulsrx** [PeterouZh/CIPS-3D#12]
Hi, excellent work!  I wonder how to trans the result to 3D mesh, just like shape_extraction.py in pi-GAN, thanks!

**Comment by PeterouZh** [comment]
Because our code is based on pi-GAN, the script should also be applicable to our method.

**Comment by rainsoulsrx** [comment]
> Because our code is based on pi-GAN, the script should also be applicable to our method.

Thanks for your reply~
However, I can not run the script in pi-GAN using CIPS-3D model, can you kindly provide an example? Thanks!

**Comment by shoutOutYangJie** [comment]
what effect do "shape_extraction" show?

**Comment by jjj12zcs** [comment]
> > Because our code is based on pi-GAN, the script should also be applicable to our method.
> 
> Thanks for your reply~ However, I can not run the script in pi-GAN using CIPS-3D model, can you kindly provide an example? Thanks!

Hi! Now I have the same problem as you. Have you solved the problem? If so, could you please tell me how you solved it?
