### ISSUE TITLE
Problem about reproducing the results

### ISSUE THREAD

**Issue by 0three** [PeterouZh/CIPS-3D#13]
Hi, PeterouZh,

I'm reproducing your results at the same pace with you. Honestly speaking, this model takes about 40 hours to reach 64x64 at FID 15.97 with 8 A100 gpus. While I change the resolution to 128x128, the FID reach to 23.58. I'm still traning it and it reach FID 20.03 yet.

How can this model reach FID 6.XX as you described in paper? Do we miss some key things? It looks that this model can only reach 10+ FID in 256 resolutions because the performance increases very lowly when the FID reach 16 at 64x64 resolution.

By the way, I try to reproduce your results few weeks ago but I met problems about moxing. Does moxing provide very important tricks for this work?

**Comment by 0three** [comment]
Thanks for your kind share and your hard work on reproducing your work in pure pytorch!

**Comment by PeterouZh** [comment]
The FID is not a standard FID during training, and it is calculated using only 2048 real images and fake images, taking into account the training efficiency. 

The FID of 6.XX described in the paper is a standard FID, which is calculated using all training images and 50,000 generated images.

**Comment by 0three** [comment]
Thank you for your professional answer! Let me regain my confidence. LOL

**Comment by 0three** [comment]
I've continue to train r128 for a day. The FID cannot drop and are around 19.5 right now.

Surprisingly, I test the FID on the whole FFHQ dataset and 50,000 generated images and get FID 6.93 in 128x128 resolution.

It looks like that the training FID will take a very long time to reach 16.

**Comment by PeterouZh** [comment]
It seems that the 128 experiment did not meet expectations. I am currently debugging.

**Comment by 0three** [comment]
Hi, I tried current sh script for training but failed.

**Comment by 0three** [comment]
May you provide a detail readme for current sh scripts?
