### ISSUE TITLE
Data format for training from scratch

### ISSUE THREAD

**Issue by hoangtnm** [PeterouZh/CIPS-3D#3]
Hi, I'm quite interested in the paper. I want to know more about format of data to train the model from scratch. Do images need to be different views of the same person from different cameras, or just random 2D images with no info about yaw/pitch are enough? thank you

**Comment by PeterouZh** [comment]
The training images are random 2D images ([FFHQ dataset](https://github.com/NVlabs/ffhq-dataset)) without info about yaw/pitch.
