### ISSUE TITLE
The quality of generated images for FFHQ

### ISSUE THREAD

**Issue by enisimsar** [PeterouZh/CIPS-3D#31]
Hello, 

Thanks for sharing your source code and pre-trained weights. I am trying to generate high-quality images from FFHQ pre-trained model. However, the quality of generated images is not as good enough as stated in the paper. I could not reproduce the results.

I am using the pre-trained weights from here https://github.com/PeterouZh/CIPS-3D/releases/tag/v0.0.2 

The command I tried: 
`python exp/cips3d/scripts/sample_images.py --tl_config_file exp/cips3d/configs/ffhq_exp.yaml --tl_command sample_images`

Generated images: 
![0048220334](https://user-images.githubusercontent.com/10683524/162332658-31c4970b-87ed-47d5-80c7-cbab9d16c6c9.jpg) ![0038712131](https://user-images.githubusercontent.com/10683524/162332661-29a19498-bfcd-437f-88a1-9676e47db8dd.jpg) ![0002215104](https://user-images.githubusercontent.com/10683524/162332662-daeaa52a-3e0f-4536-9ae3-ecefb714544f.jpg)

Do you have any idea regarding the problem?

**Comment by xuyanwu** [comment]
I got the same question

**Comment by PeterouZh** [comment]
Hi,

Thank you for your attention.
You can tune the `truncation` hyperparameter of GANs.

By the way, one way to improve generation quality is to regularize 3D shapes. I am currently training new models and will release code and models when the effect is stable.

**Comment by PeterouZh** [comment]
> I got the same question

I think the reason for the poor generation effect is the poor quality of the underlying 3D shape. I am working to solve this problem.

**Comment by enisimsar** [comment]
Does `truncation` correspond to `psi`? @PeterouZh

**Comment by PeterouZh** [comment]
> Does `truncation` correspond to `psi`? @PeterouZh

Yes.
