### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by zhywanna** [PeterouZh/CIPS-3D#32]
Dear Dr.Zhou, 
Thanks for sharing your great job and congratulations on your graduating Ph.D ! I have a few questions and hoping for your reply.

1、I found a command in another issue https://github.com/PeterouZh/CIPS-3D/issues/31#issue-1196645855 `python exp/cips3d/scripts/sample_images.py --tl_config_file exp/cips3d/configs/ffhq_exp.yaml --tl_command sample_images` But I can't find those arguments in sample_images.py and confuse about why he knows how to use. And I also found some packages import from `tl2` library, but failed to find any documentation. I wonder if there are any instruction i miss in addition to README. 
2、I saw two generators file in /CIPS-3D/exp/cips3d/models `generator.py` and `generator_v1.py`, which one should I use ? 
3、Which class in generator files indicates the complete generator module cause I want to do some inversion tests and not sure whether it's `class GeneratorNerfINR` ? And the `G_ema.pth` or `generator.pth` in ckpt is the corresponding parametors to the generator which I can directly load into, am i right?
4、What is the use of `state_dict.pth` in ckpt.

By the way, I think using Chinese is more convenience for us. Thanks!

**Comment by PeterouZh** [comment]
Most problems can be solved if you debug the training process once. 

Frankly, the current CIPS-3D implementation is not suitable for GAN inversion. The camera pose of the current implementation is not differentiable. 
If you want to do inversion, I think this paper will help you [https://arxiv.org/abs/2102.07064](https://arxiv.org/abs/2102.07064)
