### ISSUE TITLE
The pretrained model can be used in finetune_photo2cartoon.sh?

### ISSUE THREAD

**Issue by Benwang-chen** [PeterouZh/CIPS-3D#34]
I load the FFHQ pretrained model from Pre-trained checkpoints. 
And change the finetune_dir as Pre-trained checkpoints in finetune_photo2cartoon.sh. But it seems not to work. I want to know if the pre-trained model can be used in finetune_photo2cartoon.sh?

**Comment by PeterouZh** [comment]
Yes, the pre-trained ffhq model can be used for finetuning.
