### ISSUE TITLE
Configuration environment issues

### ISSUE THREAD

**Issue by Stephanie-ustc** [PeterouZh/CIPS-3D#6]
Hi,good job!

I have a problem, please help me.

pip install -e torch_fidelity_lib
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /media/sdb/wd/test_code/CIPS-3D/torch_fidelity_lib

**Comment by PeterouZh** [comment]
Could you check if there is a `setup.py` file in the `torch_fidelity_lib` directory?

If the directory is empty, I suggest you re-clone the code using the command 

`git clone --recursive https://github.com/PeterouZh/CIPS-3D.git`.

**Comment by Stephanie-ustc** [comment]
thank you！
