### ISSUE TITLE
How to test other datasets

### ISSUE THREAD

**Issue by Stephanie-ustc** [PeterouZh/CIPS-3D#7]
Hi，how to test other datasets? change the datasets/pretrained/metadata.json?

**Comment by PeterouZh** [comment]
At present, I only provide models for two datasets. More models will be provided later. 

I do not quite understand what you mean. 

Do you want to train on other datasets?

**Comment by Stephanie-ustc** [comment]
I want test some other image on your model. But I dont konw how to do it.
If I have image sequence with pose data，how to test？

**Comment by PeterouZh** [comment]
> I want test some other image on your model. But I dont konw how to do it. If I have image sequence with pose data，how to test？

1. Align the images in the way of StyleGAN. You can refer to this script [align_images.py](https://github.com/justinpinkney/stylegan2/blob/master/align_images.py).
2. Project the aligned images into the W space, also known as GAN inversion.  Different from the common 2D inversion, you'd better set an appropriate yaw/pitch/fov for the CIPS-3D generator to make the initial pose of G(w) and the image to be inverted consistent. 
3. After you get the w of the image, you can reconstruct images of different styles using G'(w). G' can be obtained by interpolating generators of different domains. 

Hope this helps.
