### ISSUE TITLE
How to test on my own image datasets?

### ISSUE THREAD

**Issue by qian5683** [PeterouZh/CIPS-3D#8]
How to test on my own image datasets?

**Comment by PeterouZh** [comment]
I'm not sure what you mean. Do you want to train on your own dataset?

**Comment by qian5683** [comment]
I want to test the model with other pictures, but I don't find a way to choose pictures

**Comment by qian5683** [comment]
> I'm not sure what you mean. Do you want to train on your own dataset?

I want to test the model with other pictures, but I don't find a way to choose pictures

**Comment by PeterouZh** [comment]
If you want to test on a real image, you first need to do GAN inversion to project the image into the w space. 

However, the inversion method for 3D GANs is not yet mature and robust. For example, it has a poor effect on the profile face with an unknown pose. 

I have no idea how to deal with this problem now. If anyone can provide a reasonable idea, maybe I can implement this function quickly. However, currently, the program does not support this feature.
