### ISSUE TITLE
Where to find full pretrained models?

### ISSUE THREAD

**Issue by abhay-sheshadri** [PeterouZh/CIPS-3D#9]
The pre-trained model files only contain generator.pth, ema.pth, and ema2.pth files.  Where can I find the other files in order to do stylization and transfer learning from CelebA onto another dataset?

**Comment by PeterouZh** [comment]
Hi, I will release all pre-trained models (generator and discriminator) so that you can finetune them on other datasets. 

However, currently, I am too busy to complete this project. I promise to complete the project after November 23, 2021. 

So sorry for the delay.
